services:
  traefik:
    ports:
      - "127.0.0.1:8881:8880"
      - "127.0.0.1:8444:8443"
      - "127.0.0.1:8081:8080"

  prometheus:
    ports:
      - "127.0.0.1:9091:9090"

  loki:
    ports:
      - "127.0.0.1:3101:3100"

  grafana:
    ports:
      - "127.0.0.1:3002:3000"
